services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: csf_server
    restart: unless-stopped
    env_file: .env.dev
    ports:
      - 8081:8081
    volumes:
      - ./server:/app
    command: python manage.py runserver 0.0.0.0:8081
