services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env.dev
    # healthcheck for sever container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: csf_server
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - 8081:8081
    volumes:
      - ./server:/app
    entrypoint: /entrypoint.sh

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: csf_client
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 8082:8082
    volumes:
      - ./client:/app

  nginx:
    image: nginx
    container_name: csf_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  watchtower:
    image: containrrr/watchtower
    container_name: csf_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
