# Generated by Django 4.2.3 on 2024-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_team_id'),
        ('users', '0012_alter_user_total_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_events',
            field=models.ManyToManyField(blank=True, to='event.event'),
        ),
    ]
