# Generated by Django 4.2.3 on 2024-02-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_total_mileage'),
        ('mileage', '0004_mileage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
