name: Backend CI

on:
  pull_request:
    types: [opened]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Set up Python Env
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.4'
