name: Backend CI

on:
  push:
    branches:
      - i52-continuous_integration_backend_automated_testing
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Setup Poetry 🏗
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache .venv 📦
        id: cached-poetry-dependencies
        uses: actions/cache@v3.0.6
        with:
          path: server/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies 👨🏻‍💻
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run Migrations 🕊️
        run: |
          source .venv/bin/activate
          python manage.py migrate

      - name: Run tests 🧪
        run: |
          source .venv/bin/activate
          coverage run manage.py test
          coverage xml

      - name: Upload Coverage ☂️
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: backend
          files: ./server/coverage.xml
