name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    # Server Docker image
    - name: Build the server Docker image
      run: docker build . --file ./docker/server/Dockerfile --tag zhanerken/cfs-prod-server:${{ steps.date.outputs.date }}
    - name: Login
      run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_TOKEN }}
    - name: Push server image
      run: docker push zhanerken/cfs-prod-server:${{ steps.date.outputs.date }}

    # Client Docker image
    - name: Build the client Docker image
      run: docker build . --file ./client/Dockerfile --tag zhanerken/cfs-prod-client:${{ steps.date.outputs.date }}
    - name: Push client image
      run: docker push zhanerken/cfs-prod-client:${{ steps.date.outputs.date }}
