name: PR Source Code Check

on:
  pull_request:
    types: [opened, edited]
    paths:
      - "**.ts"
      - "**.cjs"
      - "**.mjs"
      - "**.vue"
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn
      - run: yarn lint:strict
    defaults:
      run:
        working-directory: client

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn
      - run: yarn type-check
    defaults:
      run:
        working-directory: client

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn
      - run: yarn format:check
    defaults:
      run:
        working-directory: client
